# Cache downloaded dependencies and plugins between builds.
image:
  name: repository.dimas-maryanto.com:8086/maven:3.6-jdk-8

# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository
    
variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--show-version -s .gitlab-ci_m2.xml"

stages:
  - testing
  - build
  - deploy

test:
  services:
    - name: repository.dimas-maryanto.com:8086/postgres:12.3
      alias: postgres_db
  variables:
    POSTGRES_DB: test_data
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: test_user
    DATABASE_HOST: postgres_db
    POSTGRES_HOST_AUTH_METHOD: trust
  stage: testing
  before_script:
    - 'mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=$CI_COMMIT_TAG'
  script:
    - 'mvn $MAVEN_CLI_OPTS clean test'
  tags:
    - docker
  only:
    - /-release$/

packaging:
  stage: build
  before_script:
    - 'mvn $MAVEN_CLI_OPTS versions:set -DnewVersion=$CI_COMMIT_TAG'
  script:
    - 'mvn $MAVEN_CLI_OPTS clean package -DskipTests'
  artifacts:
    paths:
      - target/*.jar
    name: '$CI_PROJECT_PATH_SLUG-$CI_COMMIT_TAG'
  tags:
    - docker
  only:
    - /-release$/
