# This template uses jdk8 for verifying and deploying images
image:
  name: repository.dimas-maryanto.com:8086/maven:3.6-jdk-8

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

services:
  - name: repository.dimas-maryanto.com:8086/postgres:9.6
    alias: postgresql

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  POSTGRES_DB: test_data
  POSTGRES_USER: test_user
  POSTGRES_PASSWORD: test_user
  DATABASE_HOST: postgresql

stages:
  - testing
  - build
  - deploy

test:
  stage: testing
  before_script:
    - 'mvn versions:set -DnewVersion=$CI_COMMIT_TAG'
  script:
    - 'mvn clean test'
  tags:
    - docker
  only:
    - /-release$/

packaging:
  stage: build
  before_script:
    - 'mvn versions:set -DnewVersion=$CI_COMMIT_TAG'
  script:
    - 'mvn $MAVEN_CLI_OPTS clean package'
  artifacts:
    paths:
      - target/*.jar
    name: '$CI_PROJECT_PATH_SLUG-$CI_COMMIT_TAG'
  tags:
    - docker
  only:
    - /-release$/
