version: '3.7'
services:
  postgres:
    image: repository.dimas-maryanto.com:8086/postgres:9.6
    environment:
      - POSTGRES_PASSWORD=passwordnyaPostgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network
volumes:
  postgres_data:
networks:
  postgres-network:
