version: '3.7'
services:
  postgres:
    image: ${PRIVATE_REGISTRY}postgres:12.3
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network
volumes:
  postgres_data:
networks:
  postgres-network:
