version: '3.7'
services:
  springboot:
    image: ${PRIVATE_REGISTRY}example/spring-boot/springboot2-gitlab-ci-docker:2020.08.03.17.09-release
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      - postgres-network
    depends_on:
      - postgres
networks:
  postgres-network:
